### ISSUE TITLE
Add support to exchange type 'x-delayed-message'

### ISSUE THREAD

**Issue by CaioTeixeira95** [mkls/mock-amqplib#14]
Hello folks! I hope you are doing well. 👋 😃 

I'm currently working on a project that uses this awesome lib to mock the `amqp` connection and the `amqplib` instance. 🚀  
Today, we've added an exchange layer because some messages must be delayed before being consumed by the consumers. Here's an example of how we are setting things up:

```js
const connection = amqplib.connect('amqp://localhost')
const channel = connection.createChannel()

const queue = 'my-queue'
const exchange = `my-exchange-${queue}`
const binding = `${queue}-exchange-binding`

channel.assertExchange(exchange, 'x-delayed-message', {
  durable: true,
  arguments: { 'x-delayed-type': 'direct' },
})
channel.assertQueue(queue, { durable: true })
channel.bindQueue(queue, exchange, binding)
```

Here's our `jest-setup` file:

```js
beforeAll(() => {
  amqplib.connect = mockAmqplib.connect
})
```

When we try to run the tests we receive the following error:

```shell
TypeError: Cannot read properties of undefined (reading 'bindQueue')
        at Object.bindQueue (/path/to/node_modules/mock-amqplib/src/main.js:119:14)
```

That happens because on the `assertExchange` mock it doesn't match to any `type` so the `exchange` is `undefined`.

```js
// main.js:100

assertExchange: async (exchangeName, type) => {
  let exchange;

  switch(type) {
    case 'fanout':
      exchange = createFanoutExchange();
      break;
    case 'direct':
      exchange = createDirectExchange();
      break;
    case 'headers':
      exchange = createHeadersExchange();
      break;
  }

  exchanges[exchangeName] = exchange;
},
```

We did some tests using the same exchange as the case `direct` and it worked fine. So, my suggestion is to add `x-delayed-message` as the same as `direct`. We're going to have:

```js
// main.js:100

assertExchange: async (exchangeName, type) => {
  let exchange;

  switch(type) {
    case 'fanout':
      exchange = createFanoutExchange();
      break;
    case 'direct':
    case 'x-delayed-message':
      exchange = createDirectExchange();
      break;
    case 'headers':
      exchange = createHeadersExchange();
      break;
  }

  exchanges[exchangeName] = exchange;
},
```

We're using the following versions of the libs:

- amqplib: "^0.8.0"
- mock-amqplib: "^1.4.0"

What do you folks think about that? Let me know if you have any questions.

**Comment by mkls** [comment]
Hi,
This sound like a great addition to this package, but I'm currently not very active in adding new features as I no longer use it daily (we moved to google pub/sub).
That being said, If you could create a pull request for this with a test case that documents the how this new behaviour should work, I am more than happy to merge it and create a new version.

**Comment by CaioTeixeira95** [comment]
Hello @mkls, thank you for your answer! Count on me, I'll work on that! 🚀

**Comment by mkls** [comment]
This feature was added, closing this issue.
