### ISSUE TITLE
Missing functionality for `credentials`

### ISSUE THREAD

**Issue by n1md7** [mkls/mock-amqplib#16]
Hello,

The original library is exposing `credentials` alongside `connect` however it is missing here

https://github.com/amqp-node/amqplib/blob/main/channel_api.js#L15

It would be nice to have support for it.

**Comment by mkls** [comment]
Hi,

Sure, this could be added, pull requests are welcome :)

**Comment by n1md7** [comment]
Alright, I can work on it 🙂

**Comment by mkls** [comment]
The modification was merged, closing this issue.
